# Generated by Django 3.1.7 on 2021-03-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_auto_20210307_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адрес'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Тел.номер', 'verbose_name_plural': 'Тел.номер'},
        ),
    ]
