# Generated by Django 3.1.7 on 2021-03-08 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_auto_20210307_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AddField(
            model_name='company',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='date_edit',
            field=models.DateField(auto_now=True, verbose_name='Дата редактирования записи'),
        ),
    ]
