# Generated by Django 3.1.7 on 2021-03-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_auto_20210308_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-name'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
