# Generated by Django 3.1.7 on 2021-03-14 10:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_auto_20210313_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
